doctrine_migrations:
  migrations_paths:
    'Infrastructure\Migrations': '%kernel.project_dir%/src/Infrastructure'

  connection: default

#  em: default

  storage:
    table_storage:
      table_name: 'doctrine_migration_versions'
      version_column_name: 'version'
      version_column_length: 192
      executed_at_column_name: 'executed_at'
  # Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
  organize_migrations: false
  # Path to your custom migrations template
  custom_template: ~
  # Run all migrations in a transaction.
  all_or_nothing: false
  check_database_platform: true
  transactional: true
