doctrine:
  dbal:
    url: '%env(DATABASE_URL)%'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Arch:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Infrastructure/Entity'
        prefix: 'Arch\Infrastructure\Entity'
        alias: Arch
